## Real Estate - Price Predictor

In [1]:
import pandas as pd 
import numpy as np

In [2]:
housing = pd.read_csv("data1.csv")

In [3]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null int64
NOX        506 non-null float64
RM         501 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null int64
TAX        506 non-null int64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
MEDV       506 non-null float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [5]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284577   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.704799   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.887000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208000   
75%      3.677082   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [6]:
# # this shows our graps in current notebook
# %matplotlib inline

In [7]:
# # liberary used to plot all kind of graphs
# import matplotlib.pyplot as plt

In [8]:
# # hist:- will create one histogram per column .
# # bins:-Number of histogram bins to be used. If an integer is given, bins + 1 bin edges are calculated and returned.
# # figsize :-The size in inches of the figure to create.
# housing.hist(bins=50,figsize=(20,15))

# Train- Test Splitting

In [9]:
# import numpy as np

# def split_train_test(data , test_ratio):
#     # this will keep traing and testing data same no matter how mant times u run this code
#     np.random.seed(42)
#     # returns random of the given data
#     shuffled = np.random.permutation(len(data))
#     # will store the test data by given ratio
#     test_set_size = int(len(data)*test_ratio)
#     test_indices =  shuffled[:test_set_size]
#     train_indices = shuffled[test_set_size:]
#     return  data.iloc[train_indices], data.iloc[test_indices]

In [10]:
# train_set , test_set = split_train_test(housing,0.2)

In [11]:
from sklearn.model_selection import train_test_split
train_set , test_set = train_test_split(housing, test_size=0.2,random_state = 42)
print(len(train_set))

404


In [12]:
# stratifiedshuffledsplit will distribut data of "CHAS"  equaly in test and train data.
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits = 1,test_size=0.2,random_state=42)
for train_index,test_index in split.split(housing,housing['CHAS']):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]

In [13]:
strat_train_set['CHAS'].value_counts()

0    376
1     28
Name: CHAS, dtype: int64

In [14]:
housing = strat_train_set.copy()

# looking for correlation

In [15]:
# corr() function will find relation between columns
corr_matrix = housing.corr()

In [16]:
# relation with medv with others
corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.680372
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [17]:
# from pandas.plotting import scatter_matrix
# attributes = ['MEDV','RM','ZN','LSTAT']
# scatter_matrix(housing[attributes],figsize = (12,8))

In [18]:
# # here we are seeing relation between RM and MEDV in a scatter graph form
# # here kind will take graph type and alpha will take how dark are dots(0-1 range)
# housing.plot(kind="scatter",x="RM",y='MEDV',alpha=0.7)

# trying out Attributes combinations

In [19]:
# just 'TAX'/"RM" and we will put thier values in diff colm.
housing['TAXRM'] = housing['TAX']/housing['RM']

In [20]:
housing['TAXRM']

254     51.571709
348     42.200452
476    102.714374
321     45.012547
326     45.468948
          ...    
155     65.507152
423    109.126659
98      35.294118
455    102.068966
216     46.875000
Name: TAXRM, Length: 404, dtype: float64

In [21]:
corr_matrix = housing.corr()
corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.680372
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
TAXRM     -0.528014
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [22]:
# 'MEDV' col will be droped by data set
housing = strat_train_set.drop('MEDV',axis=1)
# data will be copyed in housing_labels of 'MEDV'
housing_labels = strat_train_set['MEDV'].copy()

# Missing Atributes

In [23]:
# how to desl with missing values:-
   # 1. get rid of those values
   # 2. drop that columns itself
   # 3. fill those missing values by 0 or mean or median

In [24]:
# option 1 ,here housing data will remain same 
a = housing.dropna(subset=['RM'])
a.shape

(400, 13)

In [25]:
# option 2 , here housing data will remain same
b = housing.drop('RM',axis=1)
b.shape

(404, 12)

In [26]:
# option 3 , here housing data will remain same
median = housing['RM'].median()
c = housing['RM'].fillna(median)

In [27]:
# for option 3 we have a fun in sklearn
from sklearn.impute import SimpleImputer
# in strategy we have to give mean or median or most_frequent or constant
imputer = SimpleImputer(strategy='median')
# SimpleImputer will fill whole missing values in housing data by given strategy
# the data in imputer will fit on missing values of housing data
imputer.fit(housing)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='median', verbose=0)

In [28]:
# this has median values of whole columns in housing data
imputer.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.21000e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [29]:
# Impute all missing values in hoousing
XYZ = imputer.transform(housing)

In [30]:
housing_tr = pd.DataFrame(XYZ,columns=housing.columns)

In [31]:
housing_tr.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.280886   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.712312   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086963    0.000000    5.190000    0.000000    0.453000    5.883000   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.210000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630250   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

## Sci-kit learn

3 main types objects.
1. Estimators - It estimates some parameter based on a dataset. Eg. imputer. It has a fit method and transform method. Fit method - Fits the dataset and calculates internal parameters

2. Transformers - transform method takes input and returns output based on the learnings from fit(). It also has a convenience function called fit_transform() which fits and then transforms.

3. Predictors - LinearRegression model is an example of predictor. fit() and predict() are two common functions. It also gives score() function which will evaluate the predictions.

# Feature Scaling

Primarily, two types of feature scaling methods:
1. Min-max scaling (Normalization)
    (value - min)/(max - min)
    Sklearn provides a class called MinMaxScaler for this
    
2. Standardization
    (value - mean)/std
    Sklearn provides a class called StandardScaler for this


# Creating a Pipeline

In [32]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy='median')),
    ('std_scaler',StandardScaler())
])

In [33]:
housing_num_tr = my_pipeline.fit_transform(housing)

In [34]:
housing_num_tr

array([[-0.43942006,  3.12628155, -1.12165014, ..., -0.97491834,
         0.41164221, -0.86091034],
       [-0.44352175,  3.12628155, -1.35893781, ..., -0.69277865,
         0.39131918, -0.94116739],
       [ 0.15682292, -0.4898311 ,  0.98336806, ...,  0.81196637,
         0.44624347,  0.81480158],
       ...,
       [-0.43525657, -0.4898311 , -1.23083158, ..., -0.22254583,
         0.41831233, -1.27603303],
       [ 0.14210728, -0.4898311 ,  0.98336806, ...,  0.81196637,
        -3.15239177,  0.73869575],
       [-0.43974024, -0.4898311 ,  0.37049623, ..., -0.97491834,
         0.41070422,  0.09940681]])

In [35]:
housing_num_tr.shape

(404, 13)

# Selecting a desired model for Dragon Real Estates

In [36]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
# model = LinearRegression()
# model = DecisionTreeRegressor()
model = RandomForestRegressor()
model.fit(housing_num_tr,housing_labels)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [37]:
some_data = housing.iloc[:5]
some_data

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
254  0.04819  80.0   3.64     0  0.392  6.108  32.0  9.2203    1  315   
348  0.01501  80.0   2.01     0  0.435  6.635  29.7  8.3440    4  280   
476  4.87141   0.0  18.10     0  0.614  6.484  93.6  2.3053   24  666   
321  0.18159   0.0   7.38     0  0.493  6.376  54.3  4.5404    5  287   
326  0.30347   0.0   7.38     0  0.493  6.312  28.9  5.4159    5  287   

     PTRATIO       B  LSTAT  
254     16.4  392.89   6.57  
348     17.0  390.94   5.99  
476     20.2  396.21  18.68  
321     19.6  396.90   6.87  
326     19.6  396.90   6.15

In [38]:
some_labels = housing_labels.iloc[:5]
some_labels

254    21.9
348    24.5
476    16.7
321    23.1
326    23.0
Name: MEDV, dtype: float64

In [39]:
prepared_data = my_pipeline.transform(some_data)

In [40]:
model.predict(prepared_data)

array([22.36, 25.16, 17.2 , 23.5 , 23.47])

# Evaluating the model

In [41]:
from sklearn.metrics import mean_squared_error
housing_predictions = model.predict(housing_num_tr)
mse = mean_squared_error(housing_labels,housing_predictions)
rmse = np.sqrt(mse)

In [42]:
rmse

1.459126111719268

# Using better evalution technique - Cross Validation

In [43]:
from sklearn.model_selection import cross_val_score
# where ever we get 0 error ot overfit data we will use cross_val_score 
scores = cross_val_score(model,housing_num_tr,housing_labels,scoring='neg_mean_squared_error',cv=10)
rmse_scores = np.sqrt(-scores)

In [44]:
rmse_scores

array([3.13417745, 2.98250263, 4.2140543 , 2.57257961, 3.86808092,
       2.47354654, 5.06714959, 3.81583117, 3.13205085, 2.98438687])

In [45]:
def print_scores(scores):
    print('Scores:',scores)
    print('mean:',scores.mean())
    print('Standard deviation:',scores.std())

In [46]:
print_scores(rmse_scores)

Scores: [3.13417745 2.98250263 4.2140543  2.57257961 3.86808092 2.47354654
 5.06714959 3.81583117 3.13205085 2.98438687]
mean: 3.42443599362164
Standard deviation: 0.7655425208297243


# Saving the model

In [47]:
from joblib import dump, load
dump(model,'Dragon.joblib')

['Dragon.joblib']

# Testing the model on text data

In [48]:
X_test = strat_test_set.drop('MEDV',axis=1)
Y_test = strat_test_set['MEDV'].copy()
X_test_prepared = my_pipeline.transform(X_test)
final_predictions = model.predict(X_test_prepared)
final_mse = mean_squared_error(Y_test,final_predictions)
final_rmse = np.sqrt(final_mse)

In [49]:
# final error should be very less or more near to zero.
final_rmse

2.9154473641850114